// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CGRAPH_GGML_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_CGRAPH_GGML_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace GGML {
namespace Serialization {

struct TensorDimensions;

struct TensorStrides;

struct SerializedTensor;
struct SerializedTensorBuilder;

struct HashSet;
struct HashSetBuilder;

struct SerializedCGraph;
struct SerializedCGraphBuilder;

enum TensorType : uint8_t {
  TensorType_F32 = 0,
  TensorType_F16 = 1,
  TensorType_Q4_0 = 2,
  TensorType_Q4_1 = 3,
  TensorType_Q5_0 = 6,
  TensorType_Q5_1 = 7,
  TensorType_Q8_0 = 8,
  TensorType_Q8_1 = 9,
  TensorType_Q2_K = 10,
  TensorType_Q3_K = 11,
  TensorType_Q4_K = 12,
  TensorType_Q5_K = 13,
  TensorType_Q6_K = 14,
  TensorType_Q8_K = 15,
  TensorType_IQ2_XXS = 16,
  TensorType_IQ2_XS = 17,
  TensorType_IQ3_XXS = 18,
  TensorType_IQ1_S = 19,
  TensorType_IQ4_NL = 20,
  TensorType_IQ3_S = 21,
  TensorType_IQ2_S = 22,
  TensorType_IQ4_XS = 23,
  TensorType_I8 = 24,
  TensorType_I16 = 25,
  TensorType_I32 = 26,
  TensorType_I64 = 27,
  TensorType_F64 = 28,
  TensorType_IQ1_M = 29,
  TensorType_BF16 = 30,
  TensorType_Q4_0_4_4 = 31,
  TensorType_Q4_0_4_8 = 32,
  TensorType_Q4_0_8_8 = 33,
  TensorType_TQ1_0 = 34,
  TensorType_TQ2_0 = 35,
  TensorType_MIN = TensorType_F32,
  TensorType_MAX = TensorType_TQ2_0
};

inline const TensorType (&EnumValuesTensorType())[34] {
  static const TensorType values[] = {
    TensorType_F32,
    TensorType_F16,
    TensorType_Q4_0,
    TensorType_Q4_1,
    TensorType_Q5_0,
    TensorType_Q5_1,
    TensorType_Q8_0,
    TensorType_Q8_1,
    TensorType_Q2_K,
    TensorType_Q3_K,
    TensorType_Q4_K,
    TensorType_Q5_K,
    TensorType_Q6_K,
    TensorType_Q8_K,
    TensorType_IQ2_XXS,
    TensorType_IQ2_XS,
    TensorType_IQ3_XXS,
    TensorType_IQ1_S,
    TensorType_IQ4_NL,
    TensorType_IQ3_S,
    TensorType_IQ2_S,
    TensorType_IQ4_XS,
    TensorType_I8,
    TensorType_I16,
    TensorType_I32,
    TensorType_I64,
    TensorType_F64,
    TensorType_IQ1_M,
    TensorType_BF16,
    TensorType_Q4_0_4_4,
    TensorType_Q4_0_4_8,
    TensorType_Q4_0_8_8,
    TensorType_TQ1_0,
    TensorType_TQ2_0
  };
  return values;
}

inline const char * const *EnumNamesTensorType() {
  static const char * const names[37] = {
    "F32",
    "F16",
    "Q4_0",
    "Q4_1",
    "",
    "",
    "Q5_0",
    "Q5_1",
    "Q8_0",
    "Q8_1",
    "Q2_K",
    "Q3_K",
    "Q4_K",
    "Q5_K",
    "Q6_K",
    "Q8_K",
    "IQ2_XXS",
    "IQ2_XS",
    "IQ3_XXS",
    "IQ1_S",
    "IQ4_NL",
    "IQ3_S",
    "IQ2_S",
    "IQ4_XS",
    "I8",
    "I16",
    "I32",
    "I64",
    "F64",
    "IQ1_M",
    "BF16",
    "Q4_0_4_4",
    "Q4_0_4_8",
    "Q4_0_8_8",
    "TQ1_0",
    "TQ2_0",
    nullptr
  };
  return names;
}

inline const char *EnumNameTensorType(TensorType e) {
  if (::flatbuffers::IsOutRange(e, TensorType_F32, TensorType_TQ2_0)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTensorType()[index];
}

enum TensorOp : uint8_t {
  TensorOp_NONE = 0,
  TensorOp_ADD = 1,
  TensorOp_SUB = 2,
  TensorOp_MUL = 3,
  TensorOp_DIV = 4,
  TensorOp_MUL_MAT = 5,
  TensorOp_ROPE = 6,
  TensorOp_NORM = 7,
  TensorOp_SOFT_MAX = 8,
  TensorOp_RESHAPE = 9,
  TensorOp_VIEW = 10,
  TensorOp_PERMUTE = 11,
  TensorOp_TRANSPOSE = 12,
  TensorOp_CONV_1D = 13,
  TensorOp_CONV_2D = 14,
  TensorOp_POOL_1D = 15,
  TensorOp_POOL_2D = 16,
  TensorOp_GELU = 17,
  TensorOp_SILU = 18,
  TensorOp_RELU = 19,
  TensorOp_CUSTOM = 255,
  TensorOp_MIN = TensorOp_NONE,
  TensorOp_MAX = TensorOp_CUSTOM
};

inline const TensorOp (&EnumValuesTensorOp())[21] {
  static const TensorOp values[] = {
    TensorOp_NONE,
    TensorOp_ADD,
    TensorOp_SUB,
    TensorOp_MUL,
    TensorOp_DIV,
    TensorOp_MUL_MAT,
    TensorOp_ROPE,
    TensorOp_NORM,
    TensorOp_SOFT_MAX,
    TensorOp_RESHAPE,
    TensorOp_VIEW,
    TensorOp_PERMUTE,
    TensorOp_TRANSPOSE,
    TensorOp_CONV_1D,
    TensorOp_CONV_2D,
    TensorOp_POOL_1D,
    TensorOp_POOL_2D,
    TensorOp_GELU,
    TensorOp_SILU,
    TensorOp_RELU,
    TensorOp_CUSTOM
  };
  return values;
}

inline const char *EnumNameTensorOp(TensorOp e) {
  switch (e) {
    case TensorOp_NONE: return "NONE";
    case TensorOp_ADD: return "ADD";
    case TensorOp_SUB: return "SUB";
    case TensorOp_MUL: return "MUL";
    case TensorOp_DIV: return "DIV";
    case TensorOp_MUL_MAT: return "MUL_MAT";
    case TensorOp_ROPE: return "ROPE";
    case TensorOp_NORM: return "NORM";
    case TensorOp_SOFT_MAX: return "SOFT_MAX";
    case TensorOp_RESHAPE: return "RESHAPE";
    case TensorOp_VIEW: return "VIEW";
    case TensorOp_PERMUTE: return "PERMUTE";
    case TensorOp_TRANSPOSE: return "TRANSPOSE";
    case TensorOp_CONV_1D: return "CONV_1D";
    case TensorOp_CONV_2D: return "CONV_2D";
    case TensorOp_POOL_1D: return "POOL_1D";
    case TensorOp_POOL_2D: return "POOL_2D";
    case TensorOp_GELU: return "GELU";
    case TensorOp_SILU: return "SILU";
    case TensorOp_RELU: return "RELU";
    case TensorOp_CUSTOM: return "CUSTOM";
    default: return "";
  }
}

enum GraphEvalOrder : uint8_t {
  GraphEvalOrder_LEFT_TO_RIGHT = 0,
  GraphEvalOrder_RIGHT_TO_LEFT = 1,
  GraphEvalOrder_MIN = GraphEvalOrder_LEFT_TO_RIGHT,
  GraphEvalOrder_MAX = GraphEvalOrder_RIGHT_TO_LEFT
};

inline const GraphEvalOrder (&EnumValuesGraphEvalOrder())[2] {
  static const GraphEvalOrder values[] = {
    GraphEvalOrder_LEFT_TO_RIGHT,
    GraphEvalOrder_RIGHT_TO_LEFT
  };
  return values;
}

inline const char * const *EnumNamesGraphEvalOrder() {
  static const char * const names[3] = {
    "LEFT_TO_RIGHT",
    "RIGHT_TO_LEFT",
    nullptr
  };
  return names;
}

inline const char *EnumNameGraphEvalOrder(GraphEvalOrder e) {
  if (::flatbuffers::IsOutRange(e, GraphEvalOrder_LEFT_TO_RIGHT, GraphEvalOrder_RIGHT_TO_LEFT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGraphEvalOrder()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) TensorDimensions FLATBUFFERS_FINAL_CLASS {
 private:
  int64_t ne0_;
  int64_t ne1_;
  int64_t ne2_;
  int64_t ne3_;

 public:
  TensorDimensions()
      : ne0_(0),
        ne1_(0),
        ne2_(0),
        ne3_(0) {
  }
  TensorDimensions(int64_t _ne0, int64_t _ne1, int64_t _ne2, int64_t _ne3)
      : ne0_(::flatbuffers::EndianScalar(_ne0)),
        ne1_(::flatbuffers::EndianScalar(_ne1)),
        ne2_(::flatbuffers::EndianScalar(_ne2)),
        ne3_(::flatbuffers::EndianScalar(_ne3)) {
  }
  int64_t ne0() const {
    return ::flatbuffers::EndianScalar(ne0_);
  }
  int64_t ne1() const {
    return ::flatbuffers::EndianScalar(ne1_);
  }
  int64_t ne2() const {
    return ::flatbuffers::EndianScalar(ne2_);
  }
  int64_t ne3() const {
    return ::flatbuffers::EndianScalar(ne3_);
  }
};
FLATBUFFERS_STRUCT_END(TensorDimensions, 32);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) TensorStrides FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t nb0_;
  uint64_t nb1_;
  uint64_t nb2_;
  uint64_t nb3_;

 public:
  TensorStrides()
      : nb0_(0),
        nb1_(0),
        nb2_(0),
        nb3_(0) {
  }
  TensorStrides(uint64_t _nb0, uint64_t _nb1, uint64_t _nb2, uint64_t _nb3)
      : nb0_(::flatbuffers::EndianScalar(_nb0)),
        nb1_(::flatbuffers::EndianScalar(_nb1)),
        nb2_(::flatbuffers::EndianScalar(_nb2)),
        nb3_(::flatbuffers::EndianScalar(_nb3)) {
  }
  uint64_t nb0() const {
    return ::flatbuffers::EndianScalar(nb0_);
  }
  uint64_t nb1() const {
    return ::flatbuffers::EndianScalar(nb1_);
  }
  uint64_t nb2() const {
    return ::flatbuffers::EndianScalar(nb2_);
  }
  uint64_t nb3() const {
    return ::flatbuffers::EndianScalar(nb3_);
  }
};
FLATBUFFERS_STRUCT_END(TensorStrides, 32);

struct SerializedTensor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SerializedTensorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_NE = 6,
    VT_NB = 8,
    VT_OP = 10,
    VT_OP_PARAMS = 12,
    VT_FLAGS = 14,
    VT_SRC = 16,
    VT_VIEW_SRC = 18,
    VT_VIEW_OFFS = 20,
    VT_DATA_OFFSET = 22,
    VT_DATA_SIZE = 24,
    VT_NAME = 26
  };
  GGML::Serialization::TensorType type() const {
    return static_cast<GGML::Serialization::TensorType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  const GGML::Serialization::TensorDimensions *ne() const {
    return GetStruct<const GGML::Serialization::TensorDimensions *>(VT_NE);
  }
  const GGML::Serialization::TensorStrides *nb() const {
    return GetStruct<const GGML::Serialization::TensorStrides *>(VT_NB);
  }
  GGML::Serialization::TensorOp op() const {
    return static_cast<GGML::Serialization::TensorOp>(GetField<uint8_t>(VT_OP, 0));
  }
  const ::flatbuffers::Vector<int32_t> *op_params() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_OP_PARAMS);
  }
  int32_t flags() const {
    return GetField<int32_t>(VT_FLAGS, 0);
  }
  const ::flatbuffers::Vector<uint32_t> *src() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_SRC);
  }
  uint32_t view_src() const {
    return GetField<uint32_t>(VT_VIEW_SRC, 0);
  }
  uint64_t view_offs() const {
    return GetField<uint64_t>(VT_VIEW_OFFS, 0);
  }
  uint64_t data_offset() const {
    return GetField<uint64_t>(VT_DATA_OFFSET, 0);
  }
  uint64_t data_size() const {
    return GetField<uint64_t>(VT_DATA_SIZE, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<GGML::Serialization::TensorDimensions>(verifier, VT_NE, 8) &&
           VerifyField<GGML::Serialization::TensorStrides>(verifier, VT_NB, 8) &&
           VerifyField<uint8_t>(verifier, VT_OP, 1) &&
           VerifyOffset(verifier, VT_OP_PARAMS) &&
           verifier.VerifyVector(op_params()) &&
           VerifyField<int32_t>(verifier, VT_FLAGS, 4) &&
           VerifyOffset(verifier, VT_SRC) &&
           verifier.VerifyVector(src()) &&
           VerifyField<uint32_t>(verifier, VT_VIEW_SRC, 4) &&
           VerifyField<uint64_t>(verifier, VT_VIEW_OFFS, 8) &&
           VerifyField<uint64_t>(verifier, VT_DATA_OFFSET, 8) &&
           VerifyField<uint64_t>(verifier, VT_DATA_SIZE, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct SerializedTensorBuilder {
  typedef SerializedTensor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(GGML::Serialization::TensorType type) {
    fbb_.AddElement<uint8_t>(SerializedTensor::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_ne(const GGML::Serialization::TensorDimensions *ne) {
    fbb_.AddStruct(SerializedTensor::VT_NE, ne);
  }
  void add_nb(const GGML::Serialization::TensorStrides *nb) {
    fbb_.AddStruct(SerializedTensor::VT_NB, nb);
  }
  void add_op(GGML::Serialization::TensorOp op) {
    fbb_.AddElement<uint8_t>(SerializedTensor::VT_OP, static_cast<uint8_t>(op), 0);
  }
  void add_op_params(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> op_params) {
    fbb_.AddOffset(SerializedTensor::VT_OP_PARAMS, op_params);
  }
  void add_flags(int32_t flags) {
    fbb_.AddElement<int32_t>(SerializedTensor::VT_FLAGS, flags, 0);
  }
  void add_src(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> src) {
    fbb_.AddOffset(SerializedTensor::VT_SRC, src);
  }
  void add_view_src(uint32_t view_src) {
    fbb_.AddElement<uint32_t>(SerializedTensor::VT_VIEW_SRC, view_src, 0);
  }
  void add_view_offs(uint64_t view_offs) {
    fbb_.AddElement<uint64_t>(SerializedTensor::VT_VIEW_OFFS, view_offs, 0);
  }
  void add_data_offset(uint64_t data_offset) {
    fbb_.AddElement<uint64_t>(SerializedTensor::VT_DATA_OFFSET, data_offset, 0);
  }
  void add_data_size(uint64_t data_size) {
    fbb_.AddElement<uint64_t>(SerializedTensor::VT_DATA_SIZE, data_size, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SerializedTensor::VT_NAME, name);
  }
  explicit SerializedTensorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SerializedTensor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SerializedTensor>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SerializedTensor> CreateSerializedTensor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GGML::Serialization::TensorType type = GGML::Serialization::TensorType_F32,
    const GGML::Serialization::TensorDimensions *ne = nullptr,
    const GGML::Serialization::TensorStrides *nb = nullptr,
    GGML::Serialization::TensorOp op = GGML::Serialization::TensorOp_NONE,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> op_params = 0,
    int32_t flags = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> src = 0,
    uint32_t view_src = 0,
    uint64_t view_offs = 0,
    uint64_t data_offset = 0,
    uint64_t data_size = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  SerializedTensorBuilder builder_(_fbb);
  builder_.add_data_size(data_size);
  builder_.add_data_offset(data_offset);
  builder_.add_view_offs(view_offs);
  builder_.add_name(name);
  builder_.add_view_src(view_src);
  builder_.add_src(src);
  builder_.add_flags(flags);
  builder_.add_op_params(op_params);
  builder_.add_nb(nb);
  builder_.add_ne(ne);
  builder_.add_op(op);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SerializedTensor> CreateSerializedTensorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GGML::Serialization::TensorType type = GGML::Serialization::TensorType_F32,
    const GGML::Serialization::TensorDimensions *ne = nullptr,
    const GGML::Serialization::TensorStrides *nb = nullptr,
    GGML::Serialization::TensorOp op = GGML::Serialization::TensorOp_NONE,
    const std::vector<int32_t> *op_params = nullptr,
    int32_t flags = 0,
    const std::vector<uint32_t> *src = nullptr,
    uint32_t view_src = 0,
    uint64_t view_offs = 0,
    uint64_t data_offset = 0,
    uint64_t data_size = 0,
    const char *name = nullptr) {
  auto op_params__ = op_params ? _fbb.CreateVector<int32_t>(*op_params) : 0;
  auto src__ = src ? _fbb.CreateVector<uint32_t>(*src) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return GGML::Serialization::CreateSerializedTensor(
      _fbb,
      type,
      ne,
      nb,
      op,
      op_params__,
      flags,
      src__,
      view_src,
      view_offs,
      data_offset,
      data_size,
      name__);
}

struct HashSet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HashSetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIZE = 4,
    VT_USED_BITS = 6,
    VT_KEYS = 8
  };
  uint64_t size() const {
    return GetField<uint64_t>(VT_SIZE, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *used_bits() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_USED_BITS);
  }
  const ::flatbuffers::Vector<uint32_t> *keys() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_KEYS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SIZE, 8) &&
           VerifyOffset(verifier, VT_USED_BITS) &&
           verifier.VerifyVector(used_bits()) &&
           VerifyOffset(verifier, VT_KEYS) &&
           verifier.VerifyVector(keys()) &&
           verifier.EndTable();
  }
};

struct HashSetBuilder {
  typedef HashSet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_size(uint64_t size) {
    fbb_.AddElement<uint64_t>(HashSet::VT_SIZE, size, 0);
  }
  void add_used_bits(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> used_bits) {
    fbb_.AddOffset(HashSet::VT_USED_BITS, used_bits);
  }
  void add_keys(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> keys) {
    fbb_.AddOffset(HashSet::VT_KEYS, keys);
  }
  explicit HashSetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HashSet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HashSet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HashSet> CreateHashSet(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t size = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> used_bits = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> keys = 0) {
  HashSetBuilder builder_(_fbb);
  builder_.add_size(size);
  builder_.add_keys(keys);
  builder_.add_used_bits(used_bits);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<HashSet> CreateHashSetDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t size = 0,
    const std::vector<uint8_t> *used_bits = nullptr,
    const std::vector<uint32_t> *keys = nullptr) {
  auto used_bits__ = used_bits ? _fbb.CreateVector<uint8_t>(*used_bits) : 0;
  auto keys__ = keys ? _fbb.CreateVector<uint32_t>(*keys) : 0;
  return GGML::Serialization::CreateHashSet(
      _fbb,
      size,
      used_bits__,
      keys__);
}

struct SerializedCGraph FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SerializedCGraphBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIZE = 4,
    VT_N_NODES = 6,
    VT_N_LEAFS = 8,
    VT_TENSORS = 10,
    VT_NODE_INDICES = 12,
    VT_GRAD_INDICES = 14,
    VT_GRAD_ACC_INDICES = 16,
    VT_LEAF_INDICES = 18,
    VT_USE_COUNTS = 20,
    VT_VISITED_HASH_SET = 22,
    VT_ORDER = 24,
    VT_DATA_BUFFER = 26
  };
  int32_t size() const {
    return GetField<int32_t>(VT_SIZE, 0);
  }
  int32_t n_nodes() const {
    return GetField<int32_t>(VT_N_NODES, 0);
  }
  int32_t n_leafs() const {
    return GetField<int32_t>(VT_N_LEAFS, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GGML::Serialization::SerializedTensor>> *tensors() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GGML::Serialization::SerializedTensor>> *>(VT_TENSORS);
  }
  const ::flatbuffers::Vector<uint32_t> *node_indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_NODE_INDICES);
  }
  const ::flatbuffers::Vector<uint32_t> *grad_indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_GRAD_INDICES);
  }
  const ::flatbuffers::Vector<uint32_t> *grad_acc_indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_GRAD_ACC_INDICES);
  }
  const ::flatbuffers::Vector<uint32_t> *leaf_indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_LEAF_INDICES);
  }
  const ::flatbuffers::Vector<int32_t> *use_counts() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_USE_COUNTS);
  }
  const GGML::Serialization::HashSet *visited_hash_set() const {
    return GetPointer<const GGML::Serialization::HashSet *>(VT_VISITED_HASH_SET);
  }
  GGML::Serialization::GraphEvalOrder order() const {
    return static_cast<GGML::Serialization::GraphEvalOrder>(GetField<uint8_t>(VT_ORDER, 0));
  }
  const ::flatbuffers::Vector<uint8_t> *data_buffer() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA_BUFFER);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SIZE, 4) &&
           VerifyField<int32_t>(verifier, VT_N_NODES, 4) &&
           VerifyField<int32_t>(verifier, VT_N_LEAFS, 4) &&
           VerifyOffset(verifier, VT_TENSORS) &&
           verifier.VerifyVector(tensors()) &&
           verifier.VerifyVectorOfTables(tensors()) &&
           VerifyOffset(verifier, VT_NODE_INDICES) &&
           verifier.VerifyVector(node_indices()) &&
           VerifyOffset(verifier, VT_GRAD_INDICES) &&
           verifier.VerifyVector(grad_indices()) &&
           VerifyOffset(verifier, VT_GRAD_ACC_INDICES) &&
           verifier.VerifyVector(grad_acc_indices()) &&
           VerifyOffset(verifier, VT_LEAF_INDICES) &&
           verifier.VerifyVector(leaf_indices()) &&
           VerifyOffset(verifier, VT_USE_COUNTS) &&
           verifier.VerifyVector(use_counts()) &&
           VerifyOffset(verifier, VT_VISITED_HASH_SET) &&
           verifier.VerifyTable(visited_hash_set()) &&
           VerifyField<uint8_t>(verifier, VT_ORDER, 1) &&
           VerifyOffset(verifier, VT_DATA_BUFFER) &&
           verifier.VerifyVector(data_buffer()) &&
           verifier.EndTable();
  }
};

struct SerializedCGraphBuilder {
  typedef SerializedCGraph Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_size(int32_t size) {
    fbb_.AddElement<int32_t>(SerializedCGraph::VT_SIZE, size, 0);
  }
  void add_n_nodes(int32_t n_nodes) {
    fbb_.AddElement<int32_t>(SerializedCGraph::VT_N_NODES, n_nodes, 0);
  }
  void add_n_leafs(int32_t n_leafs) {
    fbb_.AddElement<int32_t>(SerializedCGraph::VT_N_LEAFS, n_leafs, 0);
  }
  void add_tensors(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GGML::Serialization::SerializedTensor>>> tensors) {
    fbb_.AddOffset(SerializedCGraph::VT_TENSORS, tensors);
  }
  void add_node_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> node_indices) {
    fbb_.AddOffset(SerializedCGraph::VT_NODE_INDICES, node_indices);
  }
  void add_grad_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> grad_indices) {
    fbb_.AddOffset(SerializedCGraph::VT_GRAD_INDICES, grad_indices);
  }
  void add_grad_acc_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> grad_acc_indices) {
    fbb_.AddOffset(SerializedCGraph::VT_GRAD_ACC_INDICES, grad_acc_indices);
  }
  void add_leaf_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> leaf_indices) {
    fbb_.AddOffset(SerializedCGraph::VT_LEAF_INDICES, leaf_indices);
  }
  void add_use_counts(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> use_counts) {
    fbb_.AddOffset(SerializedCGraph::VT_USE_COUNTS, use_counts);
  }
  void add_visited_hash_set(::flatbuffers::Offset<GGML::Serialization::HashSet> visited_hash_set) {
    fbb_.AddOffset(SerializedCGraph::VT_VISITED_HASH_SET, visited_hash_set);
  }
  void add_order(GGML::Serialization::GraphEvalOrder order) {
    fbb_.AddElement<uint8_t>(SerializedCGraph::VT_ORDER, static_cast<uint8_t>(order), 0);
  }
  void add_data_buffer(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data_buffer) {
    fbb_.AddOffset(SerializedCGraph::VT_DATA_BUFFER, data_buffer);
  }
  explicit SerializedCGraphBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SerializedCGraph> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SerializedCGraph>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SerializedCGraph> CreateSerializedCGraph(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t size = 0,
    int32_t n_nodes = 0,
    int32_t n_leafs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GGML::Serialization::SerializedTensor>>> tensors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> node_indices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> grad_indices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> grad_acc_indices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> leaf_indices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> use_counts = 0,
    ::flatbuffers::Offset<GGML::Serialization::HashSet> visited_hash_set = 0,
    GGML::Serialization::GraphEvalOrder order = GGML::Serialization::GraphEvalOrder_LEFT_TO_RIGHT,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data_buffer = 0) {
  SerializedCGraphBuilder builder_(_fbb);
  builder_.add_data_buffer(data_buffer);
  builder_.add_visited_hash_set(visited_hash_set);
  builder_.add_use_counts(use_counts);
  builder_.add_leaf_indices(leaf_indices);
  builder_.add_grad_acc_indices(grad_acc_indices);
  builder_.add_grad_indices(grad_indices);
  builder_.add_node_indices(node_indices);
  builder_.add_tensors(tensors);
  builder_.add_n_leafs(n_leafs);
  builder_.add_n_nodes(n_nodes);
  builder_.add_size(size);
  builder_.add_order(order);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SerializedCGraph> CreateSerializedCGraphDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t size = 0,
    int32_t n_nodes = 0,
    int32_t n_leafs = 0,
    const std::vector<::flatbuffers::Offset<GGML::Serialization::SerializedTensor>> *tensors = nullptr,
    const std::vector<uint32_t> *node_indices = nullptr,
    const std::vector<uint32_t> *grad_indices = nullptr,
    const std::vector<uint32_t> *grad_acc_indices = nullptr,
    const std::vector<uint32_t> *leaf_indices = nullptr,
    const std::vector<int32_t> *use_counts = nullptr,
    ::flatbuffers::Offset<GGML::Serialization::HashSet> visited_hash_set = 0,
    GGML::Serialization::GraphEvalOrder order = GGML::Serialization::GraphEvalOrder_LEFT_TO_RIGHT,
    const std::vector<uint8_t> *data_buffer = nullptr) {
  auto tensors__ = tensors ? _fbb.CreateVector<::flatbuffers::Offset<GGML::Serialization::SerializedTensor>>(*tensors) : 0;
  auto node_indices__ = node_indices ? _fbb.CreateVector<uint32_t>(*node_indices) : 0;
  auto grad_indices__ = grad_indices ? _fbb.CreateVector<uint32_t>(*grad_indices) : 0;
  auto grad_acc_indices__ = grad_acc_indices ? _fbb.CreateVector<uint32_t>(*grad_acc_indices) : 0;
  auto leaf_indices__ = leaf_indices ? _fbb.CreateVector<uint32_t>(*leaf_indices) : 0;
  auto use_counts__ = use_counts ? _fbb.CreateVector<int32_t>(*use_counts) : 0;
  auto data_buffer__ = data_buffer ? _fbb.CreateVector<uint8_t>(*data_buffer) : 0;
  return GGML::Serialization::CreateSerializedCGraph(
      _fbb,
      size,
      n_nodes,
      n_leafs,
      tensors__,
      node_indices__,
      grad_indices__,
      grad_acc_indices__,
      leaf_indices__,
      use_counts__,
      visited_hash_set,
      order,
      data_buffer__);
}

inline const GGML::Serialization::SerializedCGraph *GetSerializedCGraph(const void *buf) {
  return ::flatbuffers::GetRoot<GGML::Serialization::SerializedCGraph>(buf);
}

inline const GGML::Serialization::SerializedCGraph *GetSizePrefixedSerializedCGraph(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GGML::Serialization::SerializedCGraph>(buf);
}

inline bool VerifySerializedCGraphBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GGML::Serialization::SerializedCGraph>(nullptr);
}

inline bool VerifySizePrefixedSerializedCGraphBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GGML::Serialization::SerializedCGraph>(nullptr);
}

inline void FinishSerializedCGraphBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GGML::Serialization::SerializedCGraph> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSerializedCGraphBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GGML::Serialization::SerializedCGraph> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Serialization
}  // namespace GGML

#endif  // FLATBUFFERS_GENERATED_CGRAPH_GGML_SERIALIZATION_H_
