set(TARGET cgraph-export)
include_directories(/home/leee/dataflow/serialization/thirdparty/flatbuffers/include)
link_directories(/home/leee/dataflow/serialization/thirdparty/flatbuffers)
add_executable(${TARGET} cgraph-export.cpp)
target_link_libraries(${TARGET} PRIVATE common llama ${CMAKE_THREAD_LIBS_INIT})
target_link_libraries(${TARGET} PRIVATE flatbuffers)

target_compile_features(${TARGET} PRIVATE cxx_std_17)
message(${CMAKE_SOURCE_DIR})
target_include_directories(${TARGET} PRIVATE ${CMAKE_SOURCE_DIR}/src)
target_include_directories(${TARGET} PRIVATE ${CMAKE_SOURCE_DIR}/ggml/src/)

if(LLAMA_TOOLS_INSTALL)
    install(TARGETS ${TARGET} RUNTIME)
endif()
